"""Initial version

Revision ID: 3f322b645369
Revises: 
Create Date: 2019-09-15 15:55:20.913138+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f322b645369'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_login')
    )
    op.create_table('inbox',
    sa.Column('inbox_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('from_user', sa.Text(), nullable=False),
    sa.Column('to_users', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('inbox_id')
    )
    op.create_table('sent',
    sa.Column('sent_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('to_users', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('sent_id')
    )
    op.bulk_insert(user_table, [
        {'user_login': 'alice@mail', },
        {'user_login': 'bob@mail', },
        {'user_login': 'jack@mail', },
        {'user_login': 'rob@mail', },
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent')
    op.drop_table('inbox')
    op.drop_table('user')
    # ### end Alembic commands ###
